// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servicenamemapping.proto

package org.apache.dubbo.registry.xds.snp;

public final class Servicenamemapping {
  private Servicenamemapping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServiceMappingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:servicenamemapping.ServiceMappingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string applicationName = 2;</code>
     * @return The applicationName.
     */
    String getApplicationName();
    /**
     * <code>string applicationName = 2;</code>
     * @return The bytes for applicationName.
     */
    com.google.protobuf.ByteString
        getApplicationNameBytes();

    /**
     * <code>repeated string interfaceName = 3;</code>
     * @return A list containing the interfaceName.
     */
    java.util.List<String>
        getInterfaceNameList();
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @return The count of interfaceName.
     */
    int getInterfaceNameCount();
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @param index The index of the element to return.
     * @return The interfaceName at the given index.
     */
    String getInterfaceName(int index);
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interfaceName at the given index.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes(int index);
  }
  /**
   * Protobuf type {@code servicenamemapping.ServiceMappingRequest}
   */
  public static final class ServiceMappingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:servicenamemapping.ServiceMappingRequest)
      ServiceMappingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceMappingRequest.newBuilder() to construct.
    private ServiceMappingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceMappingRequest() {
      namespace_ = "";
      applicationName_ = "";
      interfaceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServiceMappingRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceMappingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              applicationName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                interfaceName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              interfaceName_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          interfaceName_ = interfaceName_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceMappingRequest.class, Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    @Override
    public String getNamespace() {
      Object ref = namespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    @Override
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLICATIONNAME_FIELD_NUMBER = 2;
    private volatile Object applicationName_;
    /**
     * <code>string applicationName = 2;</code>
     * @return The applicationName.
     */
    @Override
    public String getApplicationName() {
      Object ref = applicationName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        applicationName_ = s;
        return s;
      }
    }
    /**
     * <code>string applicationName = 2;</code>
     * @return The bytes for applicationName.
     */
    @Override
    public com.google.protobuf.ByteString
        getApplicationNameBytes() {
      Object ref = applicationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        applicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList interfaceName_;
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @return A list containing the interfaceName.
     */
    public com.google.protobuf.ProtocolStringList
        getInterfaceNameList() {
      return interfaceName_;
    }
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @return The count of interfaceName.
     */
    public int getInterfaceNameCount() {
      return interfaceName_.size();
    }
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @param index The index of the element to return.
     * @return The interfaceName at the given index.
     */
    public String getInterfaceName(int index) {
      return interfaceName_.get(index);
    }
    /**
     * <code>repeated string interfaceName = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interfaceName at the given index.
     */
    public com.google.protobuf.ByteString
        getInterfaceNameBytes(int index) {
      return interfaceName_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, applicationName_);
      }
      for (int i = 0; i < interfaceName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interfaceName_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, applicationName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interfaceName_.size(); i++) {
          dataSize += computeStringSizeNoTag(interfaceName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterfaceNameList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceMappingRequest)) {
        return super.equals(obj);
      }
      ServiceMappingRequest other = (ServiceMappingRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!getApplicationName()
          .equals(other.getApplicationName())) return false;
      if (!getInterfaceNameList()
          .equals(other.getInterfaceNameList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + APPLICATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationName().hashCode();
      if (getInterfaceNameCount() > 0) {
        hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
        hash = (53 * hash) + getInterfaceNameList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceMappingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceMappingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code servicenamemapping.ServiceMappingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:servicenamemapping.ServiceMappingRequest)
        ServiceMappingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceMappingRequest.class, Builder.class);
      }

      // Construct using servicenamemapping.Servicenamemapping.ServiceMappingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        applicationName_ = "";

        interfaceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingRequest_descriptor;
      }

      @Override
      public ServiceMappingRequest getDefaultInstanceForType() {
        return ServiceMappingRequest.getDefaultInstance();
      }

      @Override
      public ServiceMappingRequest build() {
        ServiceMappingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ServiceMappingRequest buildPartial() {
        ServiceMappingRequest result = new ServiceMappingRequest(this);
        int from_bitField0_ = bitField0_;
        result.namespace_ = namespace_;
        result.applicationName_ = applicationName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          interfaceName_ = interfaceName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.interfaceName_ = interfaceName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceMappingRequest) {
          return mergeFrom((ServiceMappingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceMappingRequest other) {
        if (other == ServiceMappingRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getApplicationName().isEmpty()) {
          applicationName_ = other.applicationName_;
          onChanged();
        }
        if (!other.interfaceName_.isEmpty()) {
          if (interfaceName_.isEmpty()) {
            interfaceName_ = other.interfaceName_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInterfaceNameIsMutable();
            interfaceName_.addAll(other.interfaceName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceMappingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceMappingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public String getNamespace() {
        Object ref = namespace_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private Object applicationName_ = "";
      /**
       * <code>string applicationName = 2;</code>
       * @return The applicationName.
       */
      public String getApplicationName() {
        Object ref = applicationName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          applicationName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string applicationName = 2;</code>
       * @return The bytes for applicationName.
       */
      public com.google.protobuf.ByteString
          getApplicationNameBytes() {
        Object ref = applicationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          applicationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applicationName = 2;</code>
       * @param value The applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string applicationName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationName() {
        
        applicationName_ = getDefaultInstance().getApplicationName();
        onChanged();
        return this;
      }
      /**
       * <code>string applicationName = 2;</code>
       * @param value The bytes for applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicationName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList interfaceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInterfaceNameIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          interfaceName_ = new com.google.protobuf.LazyStringArrayList(interfaceName_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @return A list containing the interfaceName.
       */
      public com.google.protobuf.ProtocolStringList
          getInterfaceNameList() {
        return interfaceName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @return The count of interfaceName.
       */
      public int getInterfaceNameCount() {
        return interfaceName_.size();
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param index The index of the element to return.
       * @return The interfaceName at the given index.
       */
      public String getInterfaceName(int index) {
        return interfaceName_.get(index);
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the interfaceName at the given index.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes(int index) {
        return interfaceName_.getByteString(index);
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param index The index to set the value at.
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceNameIsMutable();
        interfaceName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param value The interfaceName to add.
       * @return This builder for chaining.
       */
      public Builder addInterfaceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceNameIsMutable();
        interfaceName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param values The interfaceName to add.
       * @return This builder for chaining.
       */
      public Builder addAllInterfaceName(
          Iterable<String> values) {
        ensureInterfaceNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interfaceName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        interfaceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceName = 3;</code>
       * @param value The bytes of the interfaceName to add.
       * @return This builder for chaining.
       */
      public Builder addInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInterfaceNameIsMutable();
        interfaceName_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:servicenamemapping.ServiceMappingRequest)
    }

    // @@protoc_insertion_point(class_scope:servicenamemapping.ServiceMappingRequest)
    private static final ServiceMappingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceMappingRequest();
    }

    public static ServiceMappingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceMappingRequest>
        PARSER = new com.google.protobuf.AbstractParser<ServiceMappingRequest>() {
      @Override
      public ServiceMappingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceMappingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceMappingRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceMappingRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ServiceMappingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceMappingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:servicenamemapping.ServiceMappingResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code servicenamemapping.ServiceMappingResponse}
   */
  public static final class ServiceMappingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:servicenamemapping.ServiceMappingResponse)
      ServiceMappingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceMappingResponse.newBuilder() to construct.
    private ServiceMappingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceMappingResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServiceMappingResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceMappingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceMappingResponse.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceMappingResponse)) {
        return super.equals(obj);
      }
      ServiceMappingResponse other = (ServiceMappingResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceMappingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceMappingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code servicenamemapping.ServiceMappingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:servicenamemapping.ServiceMappingResponse)
        ServiceMappingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceMappingResponse.class, Builder.class);
      }

      // Construct using servicenamemapping.Servicenamemapping.ServiceMappingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Servicenamemapping.internal_static_servicenamemapping_ServiceMappingResponse_descriptor;
      }

      @Override
      public ServiceMappingResponse getDefaultInstanceForType() {
        return ServiceMappingResponse.getDefaultInstance();
      }

      @Override
      public ServiceMappingResponse build() {
        ServiceMappingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ServiceMappingResponse buildPartial() {
        ServiceMappingResponse result = new ServiceMappingResponse(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceMappingResponse) {
          return mergeFrom((ServiceMappingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceMappingResponse other) {
        if (other == ServiceMappingResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceMappingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceMappingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:servicenamemapping.ServiceMappingResponse)
    }

    // @@protoc_insertion_point(class_scope:servicenamemapping.ServiceMappingResponse)
    private static final ServiceMappingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceMappingResponse();
    }

    public static ServiceMappingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceMappingResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceMappingResponse>() {
      @Override
      public ServiceMappingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceMappingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceMappingResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceMappingResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ServiceMappingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_servicenamemapping_ServiceMappingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_servicenamemapping_ServiceMappingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_servicenamemapping_ServiceMappingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_servicenamemapping_ServiceMappingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030servicenamemapping.proto\022\022servicenamem" +
      "apping\"Z\n\025ServiceMappingRequest\022\021\n\tnames" +
      "pace\030\001 \001(\t\022\027\n\017applicationName\030\002 \001(\t\022\025\n\ri" +
      "nterfaceName\030\003 \003(\t\"\030\n\026ServiceMappingResp" +
      "onse2\217\001\n\031ServiceNameMappingService\022r\n\031re" +
      "gisterServiceAppMapping\022).servicenamemap" +
      "ping.ServiceMappingRequest\032*.servicename" +
      "mapping.ServiceMappingResponseBDZBgithub" +
      ".com/apache/dubbo-go-pixiu/pilot/pkg/api" +
      "s/servicenamemappingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_servicenamemapping_ServiceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_servicenamemapping_ServiceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_servicenamemapping_ServiceMappingRequest_descriptor,
        new String[] { "Namespace", "ApplicationName", "InterfaceName", });
    internal_static_servicenamemapping_ServiceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_servicenamemapping_ServiceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_servicenamemapping_ServiceMappingResponse_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
