// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snp.proto

package dubbo.networking.v1alpha1;

public final class Snp {
  private Snp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServiceMappingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dubbo.networking.v1alpha1.ServiceMappingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    String getNamespace();
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string applicationName = 2;</code>
     * @return The applicationName.
     */
    String getApplicationName();
    /**
     * <code>string applicationName = 2;</code>
     * @return The bytes for applicationName.
     */
    com.google.protobuf.ByteString
        getApplicationNameBytes();

    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @return A list containing the interfaceNames.
     */
    java.util.List<String>
        getInterfaceNamesList();
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @return The count of interfaceNames.
     */
    int getInterfaceNamesCount();
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @param index The index of the element to return.
     * @return The interfaceNames at the given index.
     */
    String getInterfaceNames(int index);
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interfaceNames at the given index.
     */
    com.google.protobuf.ByteString
        getInterfaceNamesBytes(int index);
  }
  /**
   * <pre>
   * When dubbo provider start up, it reports its applicationName and its interfaceName,
   * and Dubbo consumer will get the service name mapping info by xDS.
   * </pre>
   *
   * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingRequest}
   */
  public static final class ServiceMappingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dubbo.networking.v1alpha1.ServiceMappingRequest)
      ServiceMappingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceMappingRequest.newBuilder() to construct.
    private ServiceMappingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceMappingRequest() {
      namespace_ = "";
      applicationName_ = "";
      interfaceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServiceMappingRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceMappingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              applicationName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                interfaceNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              interfaceNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          interfaceNames_ = interfaceNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceMappingRequest.class, Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile Object namespace_;
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    @Override
    public String getNamespace() {
      Object ref = namespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    @Override
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLICATIONNAME_FIELD_NUMBER = 2;
    private volatile Object applicationName_;
    /**
     * <code>string applicationName = 2;</code>
     * @return The applicationName.
     */
    @Override
    public String getApplicationName() {
      Object ref = applicationName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        applicationName_ = s;
        return s;
      }
    }
    /**
     * <code>string applicationName = 2;</code>
     * @return The bytes for applicationName.
     */
    @Override
    public com.google.protobuf.ByteString
        getApplicationNameBytes() {
      Object ref = applicationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        applicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAMES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList interfaceNames_;
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @return A list containing the interfaceNames.
     */
    public com.google.protobuf.ProtocolStringList
        getInterfaceNamesList() {
      return interfaceNames_;
    }
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @return The count of interfaceNames.
     */
    public int getInterfaceNamesCount() {
      return interfaceNames_.size();
    }
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @param index The index of the element to return.
     * @return The interfaceNames at the given index.
     */
    public String getInterfaceNames(int index) {
      return interfaceNames_.get(index);
    }
    /**
     * <code>repeated string interfaceNames = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interfaceNames at the given index.
     */
    public com.google.protobuf.ByteString
        getInterfaceNamesBytes(int index) {
      return interfaceNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, applicationName_);
      }
      for (int i = 0; i < interfaceNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interfaceNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getApplicationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, applicationName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interfaceNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(interfaceNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterfaceNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceMappingRequest)) {
        return super.equals(obj);
      }
      ServiceMappingRequest other = (ServiceMappingRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!getApplicationName()
          .equals(other.getApplicationName())) return false;
      if (!getInterfaceNamesList()
          .equals(other.getInterfaceNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + APPLICATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationName().hashCode();
      if (getInterfaceNamesCount() > 0) {
        hash = (37 * hash) + INTERFACENAMES_FIELD_NUMBER;
        hash = (53 * hash) + getInterfaceNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceMappingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceMappingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * When dubbo provider start up, it reports its applicationName and its interfaceName,
     * and Dubbo consumer will get the service name mapping info by xDS.
     * </pre>
     *
     * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dubbo.networking.v1alpha1.ServiceMappingRequest)
        ServiceMappingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceMappingRequest.class, Builder.class);
      }

      // Construct using dubbo.networking.v1alpha1.Snp.ServiceMappingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        applicationName_ = "";

        interfaceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor;
      }

      @Override
      public ServiceMappingRequest getDefaultInstanceForType() {
        return ServiceMappingRequest.getDefaultInstance();
      }

      @Override
      public ServiceMappingRequest build() {
        ServiceMappingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ServiceMappingRequest buildPartial() {
        ServiceMappingRequest result = new ServiceMappingRequest(this);
        int from_bitField0_ = bitField0_;
        result.namespace_ = namespace_;
        result.applicationName_ = applicationName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          interfaceNames_ = interfaceNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.interfaceNames_ = interfaceNames_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceMappingRequest) {
          return mergeFrom((ServiceMappingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceMappingRequest other) {
        if (other == ServiceMappingRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getApplicationName().isEmpty()) {
          applicationName_ = other.applicationName_;
          onChanged();
        }
        if (!other.interfaceNames_.isEmpty()) {
          if (interfaceNames_.isEmpty()) {
            interfaceNames_ = other.interfaceNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInterfaceNamesIsMutable();
            interfaceNames_.addAll(other.interfaceNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceMappingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceMappingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object namespace_ = "";
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public String getNamespace() {
        Object ref = namespace_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private Object applicationName_ = "";
      /**
       * <code>string applicationName = 2;</code>
       * @return The applicationName.
       */
      public String getApplicationName() {
        Object ref = applicationName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          applicationName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string applicationName = 2;</code>
       * @return The bytes for applicationName.
       */
      public com.google.protobuf.ByteString
          getApplicationNameBytes() {
        Object ref = applicationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          applicationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applicationName = 2;</code>
       * @param value The applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string applicationName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationName() {
        
        applicationName_ = getDefaultInstance().getApplicationName();
        onChanged();
        return this;
      }
      /**
       * <code>string applicationName = 2;</code>
       * @param value The bytes for applicationName to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicationName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList interfaceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInterfaceNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          interfaceNames_ = new com.google.protobuf.LazyStringArrayList(interfaceNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @return A list containing the interfaceNames.
       */
      public com.google.protobuf.ProtocolStringList
          getInterfaceNamesList() {
        return interfaceNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @return The count of interfaceNames.
       */
      public int getInterfaceNamesCount() {
        return interfaceNames_.size();
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param index The index of the element to return.
       * @return The interfaceNames at the given index.
       */
      public String getInterfaceNames(int index) {
        return interfaceNames_.get(index);
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the interfaceNames at the given index.
       */
      public com.google.protobuf.ByteString
          getInterfaceNamesBytes(int index) {
        return interfaceNames_.getByteString(index);
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param index The index to set the value at.
       * @param value The interfaceNames to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceNamesIsMutable();
        interfaceNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param value The interfaceNames to add.
       * @return This builder for chaining.
       */
      public Builder addInterfaceNames(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceNamesIsMutable();
        interfaceNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param values The interfaceNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllInterfaceNames(
          Iterable<String> values) {
        ensureInterfaceNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interfaceNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceNames() {
        interfaceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interfaceNames = 3;</code>
       * @param value The bytes of the interfaceNames to add.
       * @return This builder for chaining.
       */
      public Builder addInterfaceNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInterfaceNamesIsMutable();
        interfaceNames_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dubbo.networking.v1alpha1.ServiceMappingRequest)
    }

    // @@protoc_insertion_point(class_scope:dubbo.networking.v1alpha1.ServiceMappingRequest)
    private static final ServiceMappingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceMappingRequest();
    }

    public static ServiceMappingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceMappingRequest>
        PARSER = new com.google.protobuf.AbstractParser<ServiceMappingRequest>() {
      @Override
      public ServiceMappingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceMappingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceMappingRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceMappingRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ServiceMappingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceMappingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dubbo.networking.v1alpha1.ServiceMappingResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingResponse}
   */
  public static final class ServiceMappingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dubbo.networking.v1alpha1.ServiceMappingResponse)
      ServiceMappingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceMappingResponse.newBuilder() to construct.
    private ServiceMappingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceMappingResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServiceMappingResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceMappingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceMappingResponse.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceMappingResponse)) {
        return super.equals(obj);
      }
      ServiceMappingResponse other = (ServiceMappingResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceMappingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceMappingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dubbo.networking.v1alpha1.ServiceMappingResponse)
        ServiceMappingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceMappingResponse.class, Builder.class);
      }

      // Construct using dubbo.networking.v1alpha1.Snp.ServiceMappingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor;
      }

      @Override
      public ServiceMappingResponse getDefaultInstanceForType() {
        return ServiceMappingResponse.getDefaultInstance();
      }

      @Override
      public ServiceMappingResponse build() {
        ServiceMappingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ServiceMappingResponse buildPartial() {
        ServiceMappingResponse result = new ServiceMappingResponse(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceMappingResponse) {
          return mergeFrom((ServiceMappingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceMappingResponse other) {
        if (other == ServiceMappingResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceMappingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceMappingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dubbo.networking.v1alpha1.ServiceMappingResponse)
    }

    // @@protoc_insertion_point(class_scope:dubbo.networking.v1alpha1.ServiceMappingResponse)
    private static final ServiceMappingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceMappingResponse();
    }

    public static ServiceMappingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceMappingResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceMappingResponse>() {
      @Override
      public ServiceMappingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceMappingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceMappingResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceMappingResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ServiceMappingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceMappingXdsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dubbo.networking.v1alpha1.ServiceMappingXdsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    String getNamespace();
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string interfaceName = 2;</code>
     * @return The interfaceName.
     */
    String getInterfaceName();
    /**
     * <code>string interfaceName = 2;</code>
     * @return The bytes for interfaceName.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>repeated string applicationNames = 3;</code>
     * @return A list containing the applicationNames.
     */
    java.util.List<String>
        getApplicationNamesList();
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @return The count of applicationNames.
     */
    int getApplicationNamesCount();
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @param index The index of the element to return.
     * @return The applicationNames at the given index.
     */
    String getApplicationNames(int index);
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the applicationNames at the given index.
     */
    com.google.protobuf.ByteString
        getApplicationNamesBytes(int index);
  }
  /**
   * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingXdsResponse}
   */
  public static final class ServiceMappingXdsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dubbo.networking.v1alpha1.ServiceMappingXdsResponse)
      ServiceMappingXdsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceMappingXdsResponse.newBuilder() to construct.
    private ServiceMappingXdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceMappingXdsResponse() {
      namespace_ = "";
      interfaceName_ = "";
      applicationNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServiceMappingXdsResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceMappingXdsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              interfaceName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                applicationNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              applicationNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          applicationNames_ = applicationNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceMappingXdsResponse.class, Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile Object namespace_;
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    @Override
    public String getNamespace() {
      Object ref = namespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * This is namespace of proxyless dubbo server
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    @Override
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 2;
    private volatile Object interfaceName_;
    /**
     * <code>string interfaceName = 2;</code>
     * @return The interfaceName.
     */
    @Override
    public String getInterfaceName() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <code>string interfaceName = 2;</code>
     * @return The bytes for interfaceName.
     */
    @Override
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLICATIONNAMES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList applicationNames_;
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @return A list containing the applicationNames.
     */
    public com.google.protobuf.ProtocolStringList
        getApplicationNamesList() {
      return applicationNames_;
    }
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @return The count of applicationNames.
     */
    public int getApplicationNamesCount() {
      return applicationNames_.size();
    }
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @param index The index of the element to return.
     * @return The applicationNames at the given index.
     */
    public String getApplicationNames(int index) {
      return applicationNames_.get(index);
    }
    /**
     * <code>repeated string applicationNames = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the applicationNames at the given index.
     */
    public com.google.protobuf.ByteString
        getApplicationNamesBytes(int index) {
      return applicationNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceName_);
      }
      for (int i = 0; i < applicationNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicationNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < applicationNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(applicationNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getApplicationNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceMappingXdsResponse)) {
        return super.equals(obj);
      }
      ServiceMappingXdsResponse other = (ServiceMappingXdsResponse) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!getInterfaceName()
          .equals(other.getInterfaceName())) return false;
      if (!getApplicationNamesList()
          .equals(other.getApplicationNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      if (getApplicationNamesCount() > 0) {
        hash = (37 * hash) + APPLICATIONNAMES_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceMappingXdsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingXdsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingXdsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingXdsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingXdsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceMappingXdsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceMappingXdsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingXdsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingXdsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceMappingXdsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceMappingXdsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceMappingXdsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceMappingXdsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dubbo.networking.v1alpha1.ServiceMappingXdsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dubbo.networking.v1alpha1.ServiceMappingXdsResponse)
        ServiceMappingXdsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceMappingXdsResponse.class, Builder.class);
      }

      // Construct using dubbo.networking.v1alpha1.Snp.ServiceMappingXdsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        interfaceName_ = "";

        applicationNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Snp.internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor;
      }

      @Override
      public ServiceMappingXdsResponse getDefaultInstanceForType() {
        return ServiceMappingXdsResponse.getDefaultInstance();
      }

      @Override
      public ServiceMappingXdsResponse build() {
        ServiceMappingXdsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ServiceMappingXdsResponse buildPartial() {
        ServiceMappingXdsResponse result = new ServiceMappingXdsResponse(this);
        int from_bitField0_ = bitField0_;
        result.namespace_ = namespace_;
        result.interfaceName_ = interfaceName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          applicationNames_ = applicationNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.applicationNames_ = applicationNames_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceMappingXdsResponse) {
          return mergeFrom((ServiceMappingXdsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceMappingXdsResponse other) {
        if (other == ServiceMappingXdsResponse.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          onChanged();
        }
        if (!other.applicationNames_.isEmpty()) {
          if (applicationNames_.isEmpty()) {
            applicationNames_ = other.applicationNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureApplicationNamesIsMutable();
            applicationNames_.addAll(other.applicationNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceMappingXdsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceMappingXdsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object namespace_ = "";
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public String getNamespace() {
        Object ref = namespace_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is namespace of proxyless dubbo server
       * </pre>
       *
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private Object interfaceName_ = "";
      /**
       * <code>string interfaceName = 2;</code>
       * @return The interfaceName.
       */
      public String getInterfaceName() {
        Object ref = interfaceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @return The bytes for interfaceName.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        
        interfaceName_ = getDefaultInstance().getInterfaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @param value The bytes for interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList applicationNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureApplicationNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          applicationNames_ = new com.google.protobuf.LazyStringArrayList(applicationNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @return A list containing the applicationNames.
       */
      public com.google.protobuf.ProtocolStringList
          getApplicationNamesList() {
        return applicationNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @return The count of applicationNames.
       */
      public int getApplicationNamesCount() {
        return applicationNames_.size();
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param index The index of the element to return.
       * @return The applicationNames at the given index.
       */
      public String getApplicationNames(int index) {
        return applicationNames_.get(index);
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the applicationNames at the given index.
       */
      public com.google.protobuf.ByteString
          getApplicationNamesBytes(int index) {
        return applicationNames_.getByteString(index);
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param index The index to set the value at.
       * @param value The applicationNames to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureApplicationNamesIsMutable();
        applicationNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param value The applicationNames to add.
       * @return This builder for chaining.
       */
      public Builder addApplicationNames(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureApplicationNamesIsMutable();
        applicationNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param values The applicationNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllApplicationNames(
          Iterable<String> values) {
        ensureApplicationNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, applicationNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationNames() {
        applicationNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string applicationNames = 3;</code>
       * @param value The bytes of the applicationNames to add.
       * @return This builder for chaining.
       */
      public Builder addApplicationNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureApplicationNamesIsMutable();
        applicationNames_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dubbo.networking.v1alpha1.ServiceMappingXdsResponse)
    }

    // @@protoc_insertion_point(class_scope:dubbo.networking.v1alpha1.ServiceMappingXdsResponse)
    private static final ServiceMappingXdsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceMappingXdsResponse();
    }

    public static ServiceMappingXdsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceMappingXdsResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceMappingXdsResponse>() {
      @Override
      public ServiceMappingXdsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceMappingXdsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceMappingXdsResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceMappingXdsResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ServiceMappingXdsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tsnp.proto\022\031dubbo.networking.v1alpha1\"[" +
      "\n\025ServiceMappingRequest\022\021\n\tnamespace\030\001 \001" +
      "(\t\022\027\n\017applicationName\030\002 \001(\t\022\026\n\016interface" +
      "Names\030\003 \003(\t\"\030\n\026ServiceMappingResponse\"_\n" +
      "\031ServiceMappingXdsResponse\022\021\n\tnamespace\030" +
      "\001 \001(\t\022\025\n\rinterfaceName\030\002 \001(\t\022\030\n\020applicat" +
      "ionNames\030\003 \003(\t2\236\001\n\031ServiceNameMappingSer" +
      "vice\022\200\001\n\031registerServiceAppMapping\0220.dub" +
      "bo.networking.v1alpha1.ServiceMappingReq" +
      "uest\0321.dubbo.networking.v1alpha1.Service" +
      "MappingResponseB\035Z\033istio.io/api/dubbo/v1" +
      "alpha1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_networking_v1alpha1_ServiceMappingRequest_descriptor,
        new String[] { "Namespace", "ApplicationName", "InterfaceNames", });
    internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_networking_v1alpha1_ServiceMappingResponse_descriptor,
        new String[] { });
    internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_networking_v1alpha1_ServiceMappingXdsResponse_descriptor,
        new String[] { "Namespace", "InterfaceName", "ApplicationNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
